# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Algorithmes pour la détection de plagiat de texte en C++
NULL

rcpp_hello_world <- function() {
    .Call(`_PlagiatDetect_rcpp_hello_world`)
}

#' Fonction changeant les majuscules en minuscules en C++
#'
#' @params 1 caractère
#' @return 1 carcatère
#' @export
cpp_to_lowercase <- function(c) {
    .Call(`_PlagiatDetect_cpp_to_lowercase`, c)
}

#' Fonction transformant un texte en vecteur de phrases en C++
#'
#' @params 1 chaîne de caractères (longueur texte)
#' @return un vecteur de chaînes de caractères (longueur phrases)
#' @export
cpp_tokenizer <- function(texte) {
    .Call(`_PlagiatDetect_cpp_tokenizer`, texte)
}

#' Fonction pour accéder à la longueur d'une chaîne de caractères en C++
#'
#' @params 1 chaîne de caractères
#' @return un entier représentant la longueur de la chaîne de caractères
#' @export
cpp_get_length <- function(texte) {
    .Call(`_PlagiatDetect_cpp_get_length`, texte)
}

#' Fonction distance de Levenshtein en C++
#'
#' @params 2 chaînes de caractères
#' @return un entier représentation la distance entre les 2 chaînes de caractères
#' @export
cpp_Levenshtein <- function(str1, str2) {
    .Call(`_PlagiatDetect_cpp_Levenshtein`, str1, str2)
}

#' Algorithmes naïf distance de Levenshtein en C++
#'
#' @params 2 chaînes de caractères
#' @return un entier représentant la distance entre les 2 chaînes de caractères
#' @export
cpp_lev_naif <- function(texte1, texte2) {
    .Call(`_PlagiatDetect_cpp_lev_naif`, texte1, texte2)
}

#' Fonction évaluant le pourcentage de plagiat en C++
#'
#' @params 2 chaînes de caractères
#' @return un float pourcentage de plagiat entre les 2 chaînes de caractères
#' @export
cpp_plagiat_Levenshtein <- function(texte1, texte2) {
    .Call(`_PlagiatDetect_cpp_plagiat_Levenshtein`, texte1, texte2)
}

#' Fonction créant une matrice de scores en C++
#'
#' @params 2 chaînes de caractères et 1 entier
#' @return une matrice d'entiers
#' @export
cpp_scores_matrix <- function(str1, str2, gap_cost) {
    .Call(`_PlagiatDetect_cpp_scores_matrix`, str1, str2, gap_cost)
}

#' Fonction traceback en C++
#'
#' @params 1 matrice d'entiers et 1 chaîne de caractères
#' @return 1 chaîne de caractères
#' @export
cpp_Traceback <- function(scores_matrix, str1) {
    .Call(`_PlagiatDetect_cpp_Traceback`, scores_matrix, str1)
}

#' Algorithmes Smith-Waterman en C++
#'
#' @params 2 chaînes de caractères et 1 entier
#' @return une liste contenant 1 matrice d'entiers et 1 chaîne de caractères
#' @export
cpp_Smith_Waterman <- function(texte1, texte2, gap_cost) {
    .Call(`_PlagiatDetect_cpp_Smith_Waterman`, texte1, texte2, gap_cost)
}

