# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_PlagiatDetect_rcpp_hello_world`)
}

cpp_to_lowercase <- function(c) {
    .Call(`_PlagiatDetect_cpp_to_lowercase`, c)
}

delUnnecessary <- function(str) {
    .Call(`_PlagiatDetect_delUnnecessary`, str)
}

cpp_tokenizer <- function(texte) {
    .Call(`_PlagiatDetect_cpp_tokenizer`, texte)
}

