# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_PlagiatDetect_rcpp_hello_world`)
}

cpp_to_lowercase <- function(c) {
    .Call(`_PlagiatDetect_cpp_to_lowercase`, c)
}

cpp_tokenizer <- function(texte) {
    .Call(`_PlagiatDetect_cpp_tokenizer`, texte)
}

cpp_get_length <- function(texte) {
    .Call(`_PlagiatDetect_cpp_get_length`, texte)
}

cpp_Levenstein <- function(str1, str2) {
    .Call(`_PlagiatDetect_cpp_Levenstein`, str1, str2)
}

cpp_plagiat <- function(str1, str2) {
    .Call(`_PlagiatDetect_cpp_plagiat`, str1, str2)
}

Scores_matrixCpp <- function(str1, str2, gap_cost) {
    .Call(`_PlagiatDetect_Scores_matrixCpp`, str1, str2, gap_cost)
}

